#!/bin/sh

SUDOKU="../sudoku"
FLAGS="-r -D 3 -s 2"
PDIR="../puzzles1"

#
# Solved using three levels of DFS.  These puzzles
# require three levels of guessing with the current
# algorithmic solver.
#
for PNAME in                                          \
	lvl3-1 un-17 un-22                            \
	un-61 un-93 un-127 un-137 un-139 un-142       \
	un-144 un-146 un-152 un-154
do
	$SUDOKU $FLAGS -f $PDIR/$PNAME.txt
done

