#!/bin/sh

SUDOKU="../sudoku"
FLAGS="-r -D 2 -s 2"
PDIR="../puzzles1"

#
# Solved using two levels of DFS.  These puzzles
# require two levels of guessing with the current
# algorithmic solver.
# Note:  Removed un-36 un-82 un-102 11/17/19, as
# they only require -b for solution.
#
for PNAME in                                          \
	un-1 un-2 un-3 un-5 un-7 un-9 es-1 ink-1      \
	un-11 un-13 un-15 un-19 un-21 un-23 un-25     \
	un-26 un-27 un-29 un-31 un-33                 \
	un-37 un-39 un-41 un-42 un-47 un-48 un-52     \
	un-53 un-55 un-56 un-59 un-63 un-65 un-69     \
	un-72 un-73 un-75 un-79 un-83 un-85           \
	un-87 un-89 un-92 un-94 un-97 un-99           \
	un-105 un-107 un-109 un-111 un-113 un-115     \
	un-116 un-117 un-118 un-119 un-121 un-123     \
	un-125 un-129 un-130 un-131 un-133 un-135     \
	un-141 un-143 un-148 un-150                   \
	un-155 un-167 un-169 un-171 un-174 un-175     \
	un-176 un-177 un-179 un-180 un-182 un-184     \
	un-186 un-187 un-188 un-190 un-194 un-196     \
	un-198 un-200 un-201 un-202 un-204 un-206     \
	un-208 un-210 un-212 un-213 un-215 un-217     \
	un-219 un-221 un-223 un-225 un-227
do
	$SUDOKU $FLAGS -f $PDIR/$PNAME.txt
done

