#!/bin/sh

SUDOKU="../sudoku"
FLAGS="-b -s 2"
PDIR="../puzzles1"

#
# Solved as of 03/04/18, using BFS as needed.
# These puzzles previously passed.
#
for PNAME in g1 g2                                    \
	m1 m2 m3 m4 m5 m6 m7 m8 m9                    \
	m10 m11 m12 m14 m15 m16 m17 m18 m19           \
	m20 m21 m22 m23                               \
	u3s1 u5s1 u4s1 u5s2 u5s3 u5s4 u5s5 u5s7       \
	d1 d2 d5 d6 d3 d8                             \
	l2-1 l3-1 l3-2 l3-3 l3-4 l3-5 l3-6 l3-7       \
	l3-8 l3-9 l3-11 l3-12 l3-14 l3-15 l3-16 l3-17 \
	l3-18 l3-19 l3-20 l3-23 l3-26 l3-27 l3-28     \
	l3-30 l3-32 l3-33 l3-34 l3-35                 \
	cp3-1 cp4-1 cp4-2 cp4-3 cp4-4 cp4-5           \
	cp5-1 cp5-2                                   \
	m13 d9 l3-36 l3-37 cp4-6 l3-38                \
	l3-40 l3-41 l3-42 l3-43
do
	$SUDOKU $FLAGS -f $PDIR/$PNAME.txt
done

#
# Solved as of 03/04/18, using BFS as needed.
# These puzzles previously failed (without BFS).
#
for PNAME in                                          \
	d4 d7 u5s6 d10 l4-1                           \
	l4-2 l4-3 l4-4 l4-5                           \
	l4-6 l4-7 l4-8 l4-9                           \
	l4-10 l4-11 l4-12 l4-13                       \
	l4-14 l4-15 l4-16 l4-17                       \
	l4-18 l4-19 l3-10 l3-13                       \
	l4-20 l3-21 l3-22 l3-24                       \
	l3-25 l3-29 l3-31 l4-21                       \
	l4-22 l4-23 l4-24 l4-25                       \
	l4-26 l4-27 l3-39 l4-28                       \
	l3-44 l4-29 l4-30 l3-45
do
	$SUDOKU $FLAGS -f $PDIR/$PNAME.txt
done

