#!/bin/sh

SUDOKU="../sudoku"
FLAGS="-s 2"
PDIR="../puzzles1"

#
# Solved as of 02/15/06 (or later)
#
for PNAME in g1 g2                              \
	m1 m2 m3 m4 m5 m6 m7 m8 m9              \
	m10 m11 m12 m14 m15 m16 m17 m18 m19     \
	m20 m21 m22 m23                         \
	u3s1 u5s1 u4s1 u5s2 u5s3 u5s4 u5s5 u5s7
do
	$SUDOKU $FLAGS -f $PDIR/$PNAME.txt
done

#
# Solved as of 02/19/06 (pair analysis added)
#
for PNAME in d1 d2 d5 d6
do
	$SUDOKU $FLAGS -f $PDIR/$PNAME.txt
done

#
# Solved on 03/06/06 or later (modified tuple analysis added)
#
for PNAME in d3 d8
do
	$SUDOKU $FLAGS -f $PDIR/$PNAME.txt
done

#
# Solved on 01/05/12 or later
#
# Solutions to these puzzles verified by comparing with newspaper solutions:
#   l3-6 l3-7 l3-8 cp4-1
#
for PNAME in l2-1 l3-1 l3-2 l3-3 l3-4 l3-5 l3-6 l3-7  \
	l3-8 l3-9 l3-11 l3-12 l3-14 l3-15 l3-16 l3-17 \
	l3-18 l3-19 l3-20 l3-23 l3-26 l3-27 l3-28     \
	l3-30 l3-32 l3-33 l3-34 l3-35                 \
	cp3-1                                         \
	cp4-1 cp4-2 cp4-3 cp4-4 cp4-5                 \
	cp5-1 cp5-2
do
	$SUDOKU $FLAGS -f $PDIR/$PNAME.txt
done

#
# Solved on 02/12/12 or later (after dimensional analysis added)
#
# m13 needed modified tuple analysis, 236 23 36
# m13 needed serpentine analysis
#
for PNAME in m13 d9
do
	$SUDOKU $FLAGS -f $PDIR/$PNAME.txt
done

#
# Solved on 11/19/17 or later
#
for PNAME in l3-36 l3-37 cp4-6
do
	$SUDOKU $FLAGS -f $PDIR/$PNAME.txt
done

#
# Solved on 02/18/18 or later (after serpentine analysis added)
#
for PNAME in l3-38 l3-40 l3-41 l3-42 l3-43
do
	$SUDOKU $FLAGS -f $PDIR/$PNAME.txt
done

