#!/bin/sh

SUDOKU="../sudoku"
FLAGS="-b -s 2"
PDIR="../puzzles1"

#
# Solved as of 05/04/18, using BFS as needed.
# These puzzles previously passed without BFS.
#
for PNAME in g1 g2                                    \
	m1 m2 m3 m4 m5 m6 m7 m8 m9                    \
	m10 m11 m12 m14 m15 m16 m17 m18 m19           \
	m20 m21 m22 m23                               \
	u3s1 u5s1 u4s1 u5s2 u5s3 u5s4 u5s5 u5s7       \
	d1 d2 d5 d6 d3 d8                             \
	l2-1 l3-1 l3-2 l3-3 l3-4 l3-5 l3-6 l3-7       \
	l3-8 l3-9 l3-11 l3-12 l3-14 l3-15 l3-16 l3-17 \
	l3-18 l3-19 l3-20 l3-23 l3-26 l3-27 l3-28     \
	l3-30 l3-32 l3-33 l3-34 l3-35                 \
	cp3-1 cp4-1 cp4-2 cp4-3 cp4-4 cp4-5           \
	cp5-1 cp5-2                                   \
	m13 d9 l3-36 l3-37 cp4-6 l3-38                \
	l3-40 l3-41 l3-42 l3-43 l3-46                 \
	l3-48 l3-50 l3-51 l3-53 l3-55 l3-56           \
	l3-59 l3-61 l3-62 cp4-7 cp5-3 l3-63           \
	l3-66 l3-67 l3-68                             \
	l3-69 l3-70 l3-71 l3-72 l3-73 l3-74           \
	l3-75 l3-76 l2-2 md-2 md-3 md-5 ws-1 l3-79
do
	$SUDOKU $FLAGS -f $PDIR/$PNAME.txt
done

#
# Solved as of 05/04/18, using BFS as needed.
# These puzzles previously failed (without BFS).
#
for PNAME in                                          \
	d4 d7 u5s6 d10 l4-1                           \
	l4-2 l4-3 l4-4 l4-5                           \
	l4-6 l4-7 l4-8 l4-9                           \
	l4-10 l4-11 l4-12 l4-13                       \
	l4-14 l4-15 l4-16 l4-17                       \
	l4-18 l4-19 l3-10 l3-13                       \
	l4-20 l3-21 l3-22 l3-24                       \
	l3-25 l3-29 l3-31 l4-21                       \
	l4-22 l4-23 l4-24 l4-25                       \
	l4-26 l4-27 l3-39 l4-28                       \
	l3-44 l4-29 l4-30 l3-45                       \
	l3-47 l3-49 l3-52 l3-54 l3-57                 \
	l3-58 l3-60                                   \
	l4-31 l4-32 l4-33 l4-34 l4-35                 \
	l4-36 l4-37 l4-38 l4-39 l4-40                 \
	l4-41 l4-42 l4-43 l4-44 l4-45                 \
	l4-46 l4-47 l4-48 l4-49 l4-50                 \
	l4-51 l4-52                                   \
	l3-64 l3-65 l4-53 l4-54 l4-55 l4-56           \
	l4-57 l4-58 l4-59 l4-60 l4-61 l4-62           \
	l4-63 l4-64 l4-65 l4-66 l4-67 l4-68 l4-69     \
	l4-70 md-1 md-4 md-6 mep1 me-1 me-2           \
	me-3 me-4 me-5 me-6 me-7 me-8 me-9 me-10      \
	l3-77 l3-78 l3-80 l4-71 l4-72 l4-73 l4-74     \
	l4-75 l4-76 un-4 un-6 un-8 un-10
do
	$SUDOKU $FLAGS -f $PDIR/$PNAME.txt
done

